export enum Permission {
  ASSOCIADOS_READ = "associados:read",
  ASSOCIADOS_WRITE = "associados:write",
  ASSOCIADOS_DELETE = "associados:delete",
  USERS_READ = "users:read",
  USERS_WRITE = "users:write",
  USERS_DELETE = "users:delete",
  CARGOS_READ = "cargos:read",
  CARGOS_WRITE = "cargos:write",
  CARGOS_DELETE = "cargos:delete",
  FINANCEIRO_READ = "financeiro:read",
  FINANCEIRO_WRITE = "financeiro:write",
  FINANCEIRO_DELETE = "financeiro:delete",
  LOJINHA_READ = "lojinha:read",
  LOJINHA_WRITE = "lojinha:write",
  LOJINHA_DELETE = "lojinha:delete",
}
